# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668dc9ba0533ff0ca78f7c38347295ebe7cc06de2f0d99507630e150e14214bb3e021f51e6c4809f54e5542f55984554614fc700989c5e927e8b21e8dc0e2f33

test:
  secret_key_base: 4a72e486b6c312ab28002944652e4633ea1c6585ad5240345ec6419de97eaebd9fe86d6bc4eb0ec908d28c0116bfb10150586e85a8c85bd1277d51d3d931fafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
